<a href="https://colab.research.google.com/github/u2403126-gif/Internship/blob/main/DAY4/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
import numpy as np
a = np.array([1, 2, 3])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
import numpy as np
a = np.array([1, 2, 3])
b=a.shape
print(b)

(3,)


In [5]:
import numpy as np
arr2 = np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [7]:
import numpy as np
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a.shape)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
